### ISSUE TITLE
Next release: 1.3.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#126]
Planned changes (tentatively):
- [x] #117 openssh_cert: Implement use_agent option to get signing key from ssh-agent
- [x] #119 Refactor openssl_privatekey module, move add openssl_privatekey_pipe module
- [x] #123 Refactor openssl_csr module, add openssl_csr_pipe module
- [x] #129 Allow to run x509_certificate selfsigned provider without providing a CSR
- [x] #131 acme modules: fix deprecation in documentation
- [x] #132 ECC curve list order
- [x] #134 Move action_module from module_utils to plugin_utils
- [x] #112 Run tests with macOS 10.15
- [x] #135 Refactor x509_certificate module, add x509_certificate_pipe module
- [x] #139 Improve error handling in support code for cryptography backend

**Comment by felixfontein** [comment]
@MarkusTeufelberger if you can spare a bit of time, could you take a look at #119 and #123? Thanks :)

**Comment by felixfontein** [comment]
BTW, for an example of how openssl_privatekey_pipe and openssl_csr_pipe can be used in practice, see https://github.com/felixfontein/ansible-acme/blob/40ed248c7d3b18e604bf6f35aa9d9bdf56377b82/roles/acme_certificate/tasks/main.yml#L53-L117

**Comment by felixfontein** [comment]
@MarkusTeufelberger if you happen to have a bit more time to look at #142 and #135, would be very much appreciated :)

**Comment by felixfontein** [comment]
I'm making the release now.

**Comment by felixfontein** [comment]
And it's released! :tada:
