### ISSUE TITLE
Next release: 1.4.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#148]
- [ ] ~~#150 Move _info module code to module_utils, add diff support~~
- [x] #163 luks_device: allow to configure PBKDF
- [x] #166 openssl_pkcs12: allow to specify certificate bundles in other_certificates
- [x] #167 openssl_csr: allow to specify CRL distribution endpoints
- [x] #172 improve SNI support of get_certificate
- [x] #173 improve validation in acme_certificate, prevent hanging for wrong choice of challenge type

**Comment by felixfontein** [comment]
I plan to release 1.4.0 today. I would really appreciate if someone could at least review #166 and/or #167 so they can get in.

**Comment by felixfontein** [comment]
1.4.0 release is on its way.

**Comment by felixfontein** [comment]
1.4.0 has been released! :tada:
