### ISSUE TITLE
Next release: 1.5.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#177]
- [ ] #150 Move _info module code to module_utils, add diff support
- [x] #178 Deprecate multi-typed return value for acme_account_info
- [ ] ~~#184 ACME module_utils refactor~~
- [ ] ~~#186 ACME refactor 2~~
- [ ] #187 ACME module refactor

**Comment by felixfontein** [comment]
Looks like nobody wants to review the ACME and _info PRs, so I guess I'll create 1.5.0 without them. There are some features and bugfixes that have been waiting for a release for some time now...

**Comment by felixfontein** [comment]
1.5.0 has been released.

**Comment by MarkusTeufelberger** [comment]
The _info PR is just so huge and I am currently struggling a lot with motivation. :-/ Sorry.

It's definitely something I still want to see in this collection though.

**Comment by felixfontein** [comment]
@MarkusTeufelberger I fully understand, it's a rather big PR! I think it's easier to review this one commit by commit. If you want, I can create separate PRs for the first four ones, since these are independent from each other and make up the largest part of the PR. Each moves a lot of code to another place, but having that move just for one plugin is probably a lot easier to review. What do you think?
