### ISSUE TITLE
Next release: 1.6.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#194]
- [ ] #150 (Move _info module code to module_utils, add diff support) WIP, waits for #203, #204, #205, #206
- [x] #187 ACME module refactor
- [ ] #203 x509_crl_info refactor
- [ ] #204 openssl_csr_info refactor
- [ ] #205 openssl_privatekey_info refactor
- [ ] #206 x509_certififacte_info refactor

**Comment by felixfontein** [comment]
I'll release 1.6.0 tomorrow with whatever is merged by then. This makes sure that the latest release will again work with the latest ansible-core 2.11 beta.

**Comment by felixfontein** [comment]
The 1.6.0 release is in progress. Most planned things have been moved to 1.7.0; the main purpose of 1.6.0 now is to fix compatibility with the latest ansible-core 2.11 beta.
