### ISSUE TITLE
Next release: 1.7.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#209]
- [x] #150 Add diff support
- [x] #203 x509_crl_info refactor
- [x] #204 openssl_csr_info refactor
- [x] #205 openssl_privatekey_info refactor
- [x] #206 x509_certififacte_info refactor
- [x] #213 new openssh module_utils
- [x] #231 add openssl_publickey_info module
- [x] #232 x509_crl_info: allow to not enumerate revoked certificates
- [x] #233 openssl_csr_info and x509_certificate_info: return more public key information
- [x] #234 openssl_pkcs12: add cryptography backend
- [x] #236 openssh_keypair - Adding backend option and refactoring backend code

**Comment by felixfontein** [comment]
I'm creating a small bugfix release containing #217, so that it can be included in the Ansible 3.3.0 release coming this week.

**Comment by felixfontein** [comment]
1.6.1 has been released; next expected release is still 1.7.0.

**Comment by felixfontein** [comment]
Yay, we actually managed to complete everything on the checklist this time ;-) Thanks a lot to @Ajpantuso for the many reviews and all the PRs for openssh_keypair!

Ansible 4.1.0 will be released on June 8th, so we can wait with 1.7.0 up to then. I'd suggest to wait at least a week to see whether someone finds something (with all the new features), or something else comes up. Any opinions on this?

**Comment by Ajpantuso** [comment]
> Yay, we actually managed to complete everything on the checklist this time ;-) Thanks a lot to @Ajpantuso for the many reviews and all the PRs for openssh_keypair!
> 
> Ansible 4.1.0 will be released on June 8th, so we can wait with 1.7.0 up to then. I'd suggest to wait at least a week to see whether someone finds something (with all the new features), or something else comes up. Any opinions on this?

Sounds reasonable especially given the lack of activity here recently. Would be nice to have some more eyes on these.

**Comment by felixfontein** [comment]
I'm currently thinking of releasing 1.7.0 tomorrow, if nobody minds. (I've done some certificate renewals today and everything works smooth, and I'll do some more this evening. So far I only found bugs in unrelated collections :) )

**Comment by felixfontein** [comment]
Since we got two (easy to fix) bug reports today for module crashes, I think it's best to wait until these are fixed. I already created PRs to fix them (#241 and #243), would be great if someone could give them a review :)

**Comment by felixfontein** [comment]
1.7.0 has been released! \o/ Thanks a lot especially to @Ajpantuso for all the contributions and reviews! :)
